Added support for the specific user UID & GID
cloudnative-pg/charts pull request #207
Opened 2024-03-11 22:50 UTC by NigelVanHattum

Closes #206 

Added the postgresUID & GID from the [Clusterspec](https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec) to the helm template.

2024-03-11 23:07 UTC, itay-grudev requested changes
Could you please run `make docs` to generate the README? Otherwise it looks perfect.

2024-03-11 23:08 UTC, itay-grudev commented
Oh, and could you please make sure your commits ere `--signoff`ed for the DCO check?

2024-03-12 07:05 UTC, NigelVanHattum commented
Forgot the docs, I've added them.

2024-03-12 07:25 UTC, itay-grudev approved these changes

2024-03-12 07:30 UTC, merged