Add 'additionalEnvVars' to the chart
cloudnative-pg/charts pull request #303
Opened 2024-05-29 13:36 UTC by Stevenpc3

Add ability to set additional ENV vars via ```additionalEnvVars``` value.

Array containing extra environment variables which can be templated. You can add this to an additional override file or example putting this in override.yaml
```
- name: WATCH_NAMESPACE
  value: "{{ .Release.Namespace }}"
- name: MY_VAR
  value: "mySpecialKey"
```

Then deploy with ``` helm upgrade -i cnpg -n namespace-a charts/cnpg/ -f override.yaml```

will generate (partial template below)

![image](https://github.com/cloudnative-pg/charts/assets/6076207/e58d0d5d-45a2-4d6e-afcd-89d66d4ef1db)

With these logs

![image](https://github.com/cloudnative-pg/charts/assets/6076207/3ce9e72b-fe78-4ac2-a37d-15579fde5691)

2024-05-29 14:09 UTC, itay-grudev commented on charts/cloudnative-pg/Chart.yaml
> +version: "0.22.0"
Could you drop this change. We bump the version number as part of our release process. Moreover, given that this is a non-breaking change, a minor release would suffice.

2024-05-29 14:28 UTC, itay-grudev requested changes
The `cloudnative-pg.extraEnv` doesn't looks like it has an issue. Does it work with multiple values at all?

2024-05-29 14:28 UTC, itay-grudev commented on charts/cloudnative-pg/Chart.yaml
> +version: "0.22.0"
Could you drop this change. We bump the version number as part of our release process. Moreover, given that this is a non-breaking change, a minor release would suffice.

2024-05-29 14:28 UTC, itay-grudev commented on charts/cloudnative-pg/values.yaml
> +#    value: "{{ .Release.Namespace }}"
Please remove this example. It implies this is somehow officially supported - whereas it's truly not. The core team said they will look into it, but for now it remains unsupported.

2024-05-29 14:28 UTC, itay-grudev commented on charts/cloudnative-pg/values.yaml
> +additionalEnvVars: []
I believe the predominant convention is `additionalEnv`, and my colleagues love conventions.

2024-05-29 14:40 UTC, Stevenpc3 commented
> The `cloudnative-pg.extraEnv` doesn't looks like right to me. Does it work with multiple values at all?

If you further review my description you can see where I use two values and then pass them in and then highlight the results in the configmap which shows both values passed in.

2024-05-29 15:07 UTC, itay-grudev commented
> > The `cloudnative-pg.extraEnv` doesn't looks like right to me. Does it work with multiple values at all?
> 
> Yes it does work with multiple values. If you further review my description you can see where I use two values and then pass them in and then highlight the results in the configmap which shows both values passed in.

I think the check whether the value is string only makes sense when you wrap your macro in a range - i.e.:
```yaml
{{- range $e := .Values.additionalEnv }}
{{- include "cloudnative-pg.extraEnv" (dict "value" $e "context" $ ) | nindent 8 }}
{{- end }}
```

Otherwise .value will always be an array

2024-05-29 15:08 UTC, itay-grudev commented
And then why don't you always do `tpl`. If there is no `{{` sequence there wouldn't be anything to replace.

2024-05-29 17:44 UTC, Stevenpc3 commented
> > > The `cloudnative-pg.extraEnv` doesn't looks like right to me. Does it work with multiple values at all?
> > 
> > 
> > Yes it does work with multiple values. If you further review my description you can see where I use two values and then pass them in and then highlight the results in the configmap which shows both values passed in.
> 
> I think the check whether the value is string only makes sense when you wrap your macro in a range - i.e.:
> 
> ```yaml
> {{- range $e := .Values.additionalEnv }}
> {{- include "cloudnative-pg.extraEnv" (dict "value" $e "context" $ ) | nindent 8 }}
> {{- end }}
> ```
> 
> Otherwise .value will always be an array

Ranging over means I need to add my own "-" before name for list conversion.  Here is teh results of the template above and the override.yaml below.  You can see how range changed the items from a list to individial line outputs.

![image](https://github.com/cloudnative-pg/charts/assets/6076207/ddbd2b61-8288-4296-a42b-4b71d77534e7)

2024-05-29 17:48 UTC, Stevenpc3 commented
> And then why don't you always do `tpl`. If there is no `{{` sequence there wouldn't be anything to replace.

Yeah this is good.  I made this change and it works well with how I testsed below.

![image](https://github.com/cloudnative-pg/charts/assets/6076207/5bbc5a06-b6ce-4e9f-b7e1-6d87b168b8c5)

2024-05-29 18:03 UTC, Stevenpc3 commented
I simplified it and used the test cases of [] and the list above.  It appears good and not sure I can simplify any further.

2024-05-30 09:24 UTC, itay-grudev approved these changes

2024-05-30 09:29 UTC, phisco approved these changes
Awesome! Thanks @Stevenpc3 and @itay-grudev!

2024-05-30 09:40 UTC, merged