Add walStorage to cluster.yaml template so you can define walStorage for clusters
cloudnative-pg/charts pull request #312
Opened 2024-06-10 23:00 UTC by rocket357

The operator supports walStorage, but the chart does not (yet).  This PR fixes that.

2024-06-12 15:05 UTC, rocket357 commented
I'm working on an additional chart issue (https://github.com/cloudnative-pg/charts/issues/311) where having gkeEnvironment set to true causes the admission webhook in the operator to reject updates (due to applicationCredentials being also set).  I've rolled that change in here as well.  If it's preferred for me to break these out into separate PRs, please let me know!

2024-06-12 15:28 UTC, itay-grudev commented
@rocket357 Not everyone would approve, but the PR is so tiny - I'm fine with it as is. Just make sure both issues are mentioned in the PR description.

2024-06-13 08:24 UTC, itay-grudev approved these changes

2024-06-13 08:24 UTC, itay-grudev requested changes
Can you add the new parameter and a documentation line in the `values.yaml`?

2024-06-13 11:21 UTC, rocket357 commented
Requested changes have been added.  Please let me know if there's anything else that needs to be updated!

2024-06-15 16:11 UTC, itay-grudev approved these changes

2024-06-15 16:11 UTC, merged