Add namespace explicitly
cloudnative-pg/charts pull request #461
Opened 2024-12-05 15:18 UTC by CiraciNicolo

The rationale behind this PR is that there are cases where it becomes quite complicated to deploy the application unless the namespace is explicitly provided — for example, when managing the application using a GitOps approach.

2024-12-07 14:03 UTC, itay-grudev requested changes

2024-12-07 14:03 UTC, itay-grudev commented on charts/cloudnative-pg/Chart.yaml
> -version: "0.22.1"
Could you please remove this? It contradicts our release process.

2024-12-07 14:03 UTC, itay-grudev commented on charts/cluster/Chart.yaml
> -version: 0.1.0
Same thing here. Please remove it.

2024-12-07 14:18 UTC, itay-grudev reviewed
Could you also look at the test failures? Example:

```
Error: template: cluster/templates/pooler.yaml:7:16: executing "cluster/templates/pooler.yaml" at <include "cluster.namespace" .>: error calling include: template: cluster/templates/_helpers.tpl:5:16: executing "cluster.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride
```

2024-12-09 16:02 UTC, CiraciNicolo commented
I don't understand the DCO failure, the commits are signed.

2024-12-10 07:15 UTC, itay-grudev commented
One of your commits isn't, but you can manually set it to pass from [here](https://github.com/cloudnative-pg/charts/runs/34120488217).

2024-12-10 08:28 UTC, CiraciNicolo commented
No, all my commits are signed. If you notice the error is quite strange:

```
Summary

Commit sha: [ce9fad6](https://github.com/cloudnative-pg/charts/pull/461/commits/ce9fad60ab1d38a26188117ca187bb07ac007485), Author: Nicolò Ciraci, Committer: Nicolò Ciraci; Expected "Nicolò Ciraci ciraci.nicolo@gmail.com", but got "Nicolò Ciraci [ciraci.nicolo@gmail.com](mailto:ciraci.nicolo@gmail.com)".
```

![Screenshot 2024-12-10 at 09 26 41](https://github.com/user-attachments/assets/f543360d-b866-4bd6-aade-e213dd943895)

Am I missing something obvious?

2024-12-10 11:53 UTC, itay-grudev commented
No matter. This is good enough for me.

2024-12-17 11:36 UTC, merged